Feature/pn 310 ttl change to timestamp
cosminrentea/gobbler pull request #16
Opened 2017-03-21 15:51 UTC by Bogh

2017-03-21 16:01 UTC, cosminrentea requested changes

2017-03-21 16:01 UTC, cosminrentea commented on protocol/message_test.go
> +func TestMessage_IsExpired_WithNilExpires(t *testing.T) {
WithoutExplicitExpires

2017-03-21 16:01 UTC, cosminrentea commented on protocol/message_test.go
> +	aNormalMessageNoExpires = `/foo/bar,42,user01,phone01,{"user":"user01"},0,1420110000,1
should be ,, instead of ,0,    ?

2017-03-21 16:01 UTC, cosminrentea commented on protocol/message.go
> +	return m.Expires != 0 && m.Expires < time.Now().Unix()
we already know at this point in code that m.Expires != 0
condition can be simplified

2017-03-27 07:23 UTC, Bogh commented on protocol/message.go
> +	return m.Expires != 0 && m.Expires < time.Now().Unix()
Sorry. This was there before adding the condition above.

2017-03-27 08:10 UTC, marian-craciunescu requested changes

2017-03-27 08:10 UTC, marian-craciunescu commented on protocol/message_test.go
> +	a.Equal(false, (&Message{}).IsExpired())
you can use directly a.False((&Message{}).IsExpired()).

2017-03-27 08:10 UTC, marian-craciunescu commented on server/sms/nexmo_sms_sender.go
> +			"Expires": msg.Expires,
maybe also put msg.Expires in a human readable format like RFC3339

2017-03-27 08:20 UTC, marian-craciunescu approved these changes

2017-03-28 09:14 UTC, closed without merging